; ==========================================================
; Taxi Light
; ESP32-WROOM-32
; PlatformIO
; ==========================================================

[env:esp32dev]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

upload_protocol = espota
upload_port = 192.168.0.249
upload_flags =
    --auth=taxilight_ota

build_flags =
    -D CORE_DEBUG_LEVEL=0

extra_scripts = pre:scripts/build_web.py

lib_deps =
    fastled/FastLED @ ^3.9.15
    bblanchon/ArduinoJson @ ^7.4.2
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git