import gzip
import os

try:
    Import("env")
    ROOT = env.subst("$PROJECT_DIR")
except Exception:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) if "__file__" in globals() else os.getcwd()

WEB_DIR = os.path.join(ROOT, "src", "web")
INDEX_PATH = os.path.join(WEB_DIR, "index.html")
DEV_PATH = os.path.join(WEB_DIR, "dev.html")
OUTPUT_PATH = os.path.join(WEB_DIR, "web_assets.h")

def to_c_array(name, data):
    lines = [f"// {name} ({len(data)} bytes, compressed with gzip)"]
    lines.append(f"const uint8_t {name}[] PROGMEM = {{")
    chunk_size = 20
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i+chunk_size]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + chunk_size < len(data):
            lines.append(f"  {hex_bytes},")
        else:
            lines.append(f"  {hex_bytes}")
    lines.append("};")
    lines.append(f"const size_t {name}_LEN = {len(data)};\n")
    return "\n".join(lines)

def build():
    if not os.path.exists(INDEX_PATH) or not os.path.exists(DEV_PATH):
        print(f"[build_web] Warning: {INDEX_PATH} or {DEV_PATH} not found!")
        return

    with open(INDEX_PATH, "rb") as f:
        idx_raw = f.read()
    with open(DEV_PATH, "rb") as f:
        dev_raw = f.read()

    idx_gz = gzip.compress(idx_raw, compresslevel=9)
    dev_gz = gzip.compress(dev_raw, compresslevel=9)

    content = [
        "#pragma once",
        "// Auto-generated by scripts/build_web.py. Do not edit manually.",
        "#include <Arduino.h>\n",
        to_c_array("INDEX_HTML_GZ", idx_gz),
        to_c_array("DEV_HTML_GZ", dev_gz),
    ]

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    print(f"[build_web] index.html: {len(idx_raw)} -> {len(idx_gz)} bytes (-{round((1-len(idx_gz)/len(idx_raw))*100, 1)}%)")
    print(f"[build_web] dev.html:   {len(dev_raw)} -> {len(dev_gz)} bytes (-{round((1-len(dev_gz)/len(dev_raw))*100, 1)}%)")
    print(f"[build_web] Generated {OUTPUT_PATH}")

build()
